### ISSUE TITLE
Building for 32 bit Windows

### ISSUE THREAD

**Issue by thebeekeeper** [cwoodall/pcan-basic-sys#3]
Not sure if I'm doing something wrong, but when I build the library for 32-bit with `cargo build --target=i686-pc-windows-msvc` on a 64-bit machine, I end up with a 64-bit PCANBasic.lib.

I think it has to do with build.rs checking `target_arch` against the build script's target arch?  I'm pretty new with Rust and especially using native libraries, so I don't really know.  It does seem to build for 32-bit if I hardcode `let machine = "/Machine:X86";`

Thanks for making this binding library!  It's gotten me up and running much quicker than I could have on my own.

**Comment by cwoodall** [comment]
Hey I have no ideas at the moment. I might pay with it a bit, but if you have an idea of how to make this work better I would be up for it! Glad someone's using it.

**Comment by cwoodall** [comment]
@thebeekeeper confirm that prior PR worked for you
